const {agents,universal,getAgent}=require("./agents-data");
const rateStore=global.__lmRateStore||(global.__lmRateStore=new Map());
const jsonHeaders=origin=>({"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Access-Control-Allow-Origin":origin,"Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin","X-Content-Type-Options":"nosniff"});
const reply=(status,body,origin)=>({statusCode:status,headers:jsonHeaders(origin),body:JSON.stringify(body)});
function clean(value,max=500){return String(value??"").replace(/[\u0000-\u001F\u007F]/g," ").trim().slice(0,max)}
function allowedOrigin(event){const origin=event.headers.origin||event.headers.Origin||"";const host=event.headers.host||event.headers.Host||"";const permitted=[process.env.SITE_URL,`https://${host}`,`http://${host}`].filter(Boolean).map(x=>x.replace(/\/$/,""));return !origin||permitted.includes(origin.replace(/\/$/,""))?origin||"*":null}
function rateLimit(key){const now=Date.now(),windowMs=10*60e3,limit=Math.max(3,Math.min(60,Number(process.env.RATE_LIMIT_PER_10_MIN)||15));const previous=(rateStore.get(key)||[]).filter(t=>now-t<windowMs);if(previous.length>=limit)return false;previous.push(now);rateStore.set(key,previous);if(rateStore.size>5000)for(const [k,v] of rateStore)if(!v.some(t=>now-t<windowMs))rateStore.delete(k);return true}
async function authenticate(event){if(process.env.AUTH_REQUIRED!=="true")return {id:"anonymous"};const token=(event.headers.authorization||event.headers.Authorization||"").replace(/^Bearer\s+/i,"");if(!token||!process.env.SUPABASE_URL||!process.env.SUPABASE_ANON_KEY)throw Object.assign(new Error("Autenticação necessária."),{status:401});const r=await fetch(process.env.SUPABASE_URL.replace(/\/$/,"")+"/auth/v1/user",{headers:{apikey:process.env.SUPABASE_ANON_KEY,Authorization:"Bearer "+token}});if(!r.ok)throw Object.assign(new Error("Sessão inválida ou expirada."),{status:401});return r.json()}
function contextText(client){if(!client)return "Cliente: não selecionado. Analise no nível da agência.";const safe={empresa:clean(client.name,100),nicho:clean(client.niche,100),cidade:clean(client.city,100),ticket:Number(client.ticket)||0,objetivo:clean(client.goal,250),orcamento:Number(client.budget)||0};return "CONTEXTO DO CLIENTE\n"+Object.entries(safe).map(([k,v])=>`${k}: ${v||"não informado"}`).join("\n")}
function outputText(data){if(typeof data.output_text==="string")return data.output_text;return(data.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==="output_text"||x.text).map(x=>x.text||"").join("\n").trim()}
async function respond(model,instructions,input,max=1800){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),55000);try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",signal:controller.signal,headers:{"Content-Type":"application/json",Authorization:"Bearer "+process.env.OPENAI_API_KEY},body:JSON.stringify({model,instructions,input,max_output_tokens:max,store:false})});const data=await r.json();if(!r.ok)throw new Error(data.error?.message||"A OpenAI não concluiu a solicitação.");const text=outputText(data);if(!text)throw new Error("Resposta vazia do modelo.");return text}finally{clearTimeout(timer)}}
function parseRoute(text){try{const raw=text.match(/\{[\s\S]*\}/)?.[0]||text;const obj=JSON.parse(raw);const ids=[...new Set((obj.agents||[]).map(String))].filter(id=>getAgent(id)).slice(0,5);return{agents:ids.length?ids:["strategy","offer"],reason:clean(obj.reason,300)}}catch{return{agents:["strategy","offer","analytics"],reason:"Roteamento de contingência"}}}
function demoAnswer(agentId,message,client){const name=client?.name||"o negócio";if(agentId!=="cmo"){const a=getAgent(agentId);return`MODO DEMONSTRAÇÃO — ${a?.name||"Especialista"}\n\nObjetivo interpretado\n${message}\n\nRecomendação inicial para ${name}\n1. Defina uma meta numérica, prazo e capacidade máxima de atendimento.\n2. Registre a linha de base: investimento, leads, agendamentos, vendas, ticket e recorrência.\n3. Execute uma ação principal por 7 dias e compare o resultado com a linha de base.\n\nPrioridade: P1\nResponsável: ${a?.name||"Agente IA"}\nPrazo sugerido: 7 dias\nKPI: conversão até venda e custo por cliente.\n\nConecte OPENAI_API_KEY no Netlify para receber a análise completa e contextual.`};return`MODO DEMONSTRAÇÃO — CMO IA\n\nPara a demanda “${message}”, eu acionaria: Estratégia, Oferta, Tráfego Pago, WhatsApp e Performance.\n\nPLANO DE AÇÃO DO CMO — ${name}\n\nP0 — Instrumentação\nConfirme meta, prazo, margem, capacidade, investimento e conversões atuais. Sem isso, crescimento pode aumentar volume sem aumentar lucro.\n\nP1 — Oferta e aquisição\nEstruture uma oferta clara, produza 3 ângulos criativos e rode um teste controlado por 7 dias.\n\nP1 — Conversão\nImplemente resposta imediata, qualificação curta, follow-up em 2h/24h/72h e registro do motivo de perda.\n\nP1 — Medição\nAcompanhe CPL, lead→agendamento, comparecimento, venda, CAC, ticket e ROAS. Otimize primeiro a maior queda do funil.\n\nPróxima ação: registrar os números atuais e definir a meta semanal.\nKPI principal: custo por novo cliente com margem positiva.\n\nConecte OPENAI_API_KEY no Netlify para ativar a orquestração real dos especialistas.`}
async function audit(user,agentId,message,ok){if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)return;try{await fetch(process.env.SUPABASE_URL.replace(/\/$/,"")+"/rest/v1/audit_logs",{method:"POST",headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:"Bearer "+process.env.SUPABASE_SERVICE_ROLE_KEY,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id==="anonymous"?null:user.id,action:"agent_chat",entity_type:"agent",metadata:{agent_id:agentId,input_length:message.length,success:ok}})})}catch{}}
exports.handler=async(event)=>{
const origin=allowedOrigin(event);if(!origin)return reply(403,{error:"Origem não autorizada."},"null");
if(event.httpMethod==="OPTIONS")return{statusCode:204,headers:jsonHeaders(origin),body:""};
if(event.httpMethod!=="POST")return reply(405,{error:"Método não permitido."},origin);
let user={id:"anonymous"},agentId="",message="";
try{
user=await authenticate(event);const ip=event.headers["x-nf-client-connection-ip"]||event.headers["x-forwarded-for"]?.split(",")[0]||"unknown";if(!rateLimit(user.id+":"+ip))return reply(429,{error:"Limite temporário atingido. Aguarde alguns minutos."},origin);
let body;try{body=JSON.parse(event.body||"{}")}catch{return reply(400,{error:"JSON inválido."},origin)}
agentId=clean(body.agentId,40)||"cmo";message=clean(body.message,8000);if(!message)return reply(400,{error:"Informe uma mensagem."},origin);if(agentId!=="cmo"&&!getAgent(agentId))return reply(400,{error:"Agente inválido."},origin);
const client={name:clean(body.client?.name,100),niche:clean(body.client?.niche,100),city:clean(body.client?.city,100),ticket:Number(body.client?.ticket)||0,goal:clean(body.client?.goal,250),budget:Number(body.client?.budget)||0};
if(!process.env.OPENAI_API_KEY||process.env.DEMO_MODE==="true"){const answer=demoAnswer(agentId,message,client.name?client:null);await audit(user,agentId,message,true);return reply(200,{answer,mode:"demo"},origin)}
const history=(Array.isArray(body.history)?body.history:[]).slice(-8).map(x=>({role:x.role==="assistant"?"assistant":"user",content:clean(x.text,1500)}));const context=contextText(client.name?client:null);const specialistModel=process.env.OPENAI_SPECIALIST_MODEL||"gpt-5-mini";
if(agentId!=="cmo"){const agent=getAgent(agentId);const answer=await respond(specialistModel,universal+"\nSUA FUNÇÃO\n"+agent.mission,JSON.stringify([...history,{role:"user",content:context+"\n\nTAREFA\n"+message}]),1800);await audit(user,agentId,message,true);return reply(200,{answer,mode:"production",agents:[agentId]},origin)}
const routerModel=process.env.OPENAI_ROUTER_MODEL||"gpt-5-mini";const router=await respond(routerModel,`Você é o roteador do CMO da Lucas Marketing AI. Escolha de 1 a 5 especialistas estritamente necessários. IDs válidos: ${agents.map(a=>a.id).join(", ")}. Retorne somente JSON no formato {"agents":["id"],"reason":"motivo curto"}.`,context+"\n\nDEMANDA\n"+message,350);const route=parseRoute(router);
const work=await Promise.all(route.agents.map(async id=>{const a=getAgent(id);const result=await respond(specialistModel,universal+"\nSUA FUNÇÃO\n"+a.mission,context+"\n\nTAREFA DO CMO\n"+message+"\n\nEntregue sua análise especializada para o CMO.",1400);return{agent:a.name,id,result}}));
const synthesisInput=`${context}\n\nDEMANDA DO USUÁRIO\n${message}\n\nESPECIALISTAS ACIONADOS\n${work.map(x=>`## ${x.agent}\n${x.result}`).join("\n\n")}`;
const answer=await respond(process.env.OPENAI_CMO_MODEL||"gpt-5",`Você é o CMO IA da Lucas Marketing. Consolide as análises em um único plano coerente, sem repetir conteúdo. Resolva conflitos priorizando dados, receita, experiência, simplicidade e velocidade de aprendizado. Entregue: objetivo, diagnóstico, estratégia, ações em P0/P1/P2, agente responsável, prazo, KPI, riscos e próxima ação. Não afirme que executou ações externas.`,synthesisInput,2800);
await audit(user,"cmo",message,true);return reply(200,{answer,mode:"production",agents:route.agents,reason:route.reason},origin)
}catch(error){await audit(user,agentId,message,false);console.error("chat_error",{name:error.name,message:error.message,agentId});const status=error.status||((error.name==="AbortError")?504:500);return reply(status,{error:status===500?"Não foi possível concluir agora. Tente novamente em instantes.":error.message},origin)}
};